import { DrawerClient } from "@/components/drawer";

export function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`panel ${className}`}>{children}</section>; }
export function Field({ children, label }: { children: React.ReactNode; label: string }) { return <label className="grid gap-2 text-[.7rem] font-bold uppercase tracking-[.14em] text-mist">{label}{children}</label>; }
export const inputClass = "w-full rounded-xl border border-line bg-white px-3.5 py-2.5 text-sm font-normal normal-case tracking-normal text-ink outline-none transition placeholder:text-mist/50 focus:border-sage focus:ring-4 focus:ring-sage/10";
export const buttonClass = "inline-flex cursor-pointer items-center justify-center rounded-xl bg-ink px-4 py-2.5 text-sm font-semibold text-white transition hover:-translate-y-px hover:bg-sage focus:outline-none focus:ring-4 focus:ring-sage/20";
export const secondaryButtonClass = "inline-flex cursor-pointer items-center justify-center rounded-xl border border-line bg-white px-4 py-2.5 text-sm font-semibold text-ink transition hover:border-sage/40 hover:bg-sage-light";
export function Eyebrow({ children }: { children: React.ReactNode }) { return <p className="eyebrow">{children}</p>; }
export function Badge({ children, tone = "sage" }: { children: React.ReactNode; tone?: "sage" | "blush" | "gold" | "neutral" | "danger" }) { const tones = { sage: "bg-sage-light text-sage-dark", blush: "bg-blush-light text-[#956456]", gold: "bg-[#f5eee1] text-[#8e7040]", neutral: "bg-linen text-mist", danger: "bg-[#f7e7e1] text-[#a35d49]" }; return <span className={`inline-flex rounded-full px-2.5 py-1 text-[.65rem] font-bold uppercase tracking-[.1em] ${tones[tone]}`}>{children}</span>; }
export function Progress({ value }: { value: number }) { return <div className="h-1.5 overflow-hidden rounded-full bg-linen" aria-label={`${value}% complete`}><div className="h-full rounded-full bg-sage" style={{ width: `${Math.min(100, Math.max(0, value))}%` }} /></div>; }
export function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <header className="flex flex-col gap-5 border-b border-line pb-7 sm:flex-row sm:items-end sm:justify-between"><div><Eyebrow>{eyebrow}</Eyebrow><h2 className="mt-2 font-display text-4xl font-semibold leading-none text-ink sm:text-5xl">{title}</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-mist">{description}</p></div>{action}</header>; }
export function Drawer({ label, title, children, secondary = false }: { label: string; title: string; children: React.ReactNode; secondary?: boolean }) { return <DrawerClient label={label} secondary={secondary} title={title}>{children}</DrawerClient>; }
